trigger: none

variables:
#View adoCrednetials vars in ADO library
- group: adoCredentials
- name: source
  value: "../../../modules/aks/"
- name: aks_k8s_version
  value: "1.16.7"
- name: aks_location
  value: "West US 2" 
- name: aks_resource_group_name
  value: "aks-production-manage-rg"
- name: aks_cluster_name
  value: "aks-production-manage"
- name: aks_node_count
  value: 2
- name: aks_dns_prefix
  value: aks-production-manage
- name: aks_admin_username
  value: "sergeyago"
- name: terraform_task
  value: "deploy"
- name: module_manifest_name
  value: "prod_aks_large_cluster"
- name: environment 
  value: "production"

resources:
  - repo: self

stages: 
  - stage: inject
    displayName: inject variables into manifest file (main.tf)
    jobs:
    - job: 
      pool:
        vmImage: 'ubuntu-latest'
      steps:    
        - script: |
            sed -i -e "s|\${source}|$(source)|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
            sed -i -e "s|\${aksK8sVersion}|$(aks_k8s_version)|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
            sed -i -e "s|\${aksLocation}|$(aks_location )|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
            sed -i -e "s|\${aksResourceGroupName}|$(aks_resource_group_name)|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
            sed -i -e "s|\${aksClusterName}|$(aks_cluster_name)|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
            sed -i -e "s|\${aksNodeCount}|$(AKS_NODE_COUNT)|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
            sed -i -e "s|\${aksDnsPrefix}|$(aks_dns_prefix)|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
            sed -i -e "s|\${aksAdminUsername}|$(aks_admin_username)|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
            sed -i -e "s|\${aksClientId}|$(aks_client_id)|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
            sed -i -e "s|\${aksClientSecret}|$(aks_client_secret)|g" "$(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf"
  - stage: init
    dependsOn: inject
    displayName: init terraform
    jobs:
    - job: 
      pool:
        vmImage: 'ubuntu-latest'
      steps:    
        - script: |
            terraform init $(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf

  - stage: apply
    dependsOn: init
    condition: and(always(), eq('$(terraform_task)', 'deploy'))
    displayName: apply terraform
    jobs:
    - job: 
      pool:
        vmImage: 'ubuntu-latest'
      steps:    
        - script: |
            terraform apply $(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf -auto-approve

  - stage: destroy
    dependsOn: init
    displayName: destroy terraform $(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf
    jobs:
    - job: 
      pool:
        vmImage: 'ubuntu-latest'
      steps:    
        - script: |
            terraform destroy -auto-approve -path $(Pipeline.Workspace)/s/environment/$(environment)/$(module_manifest_name)/main.tf


