variable "azure_client_id" {}
variable "azure_client_secret" {}
variable aks_location {}
variable aks_resource_group_name {}
variable aks_cluster_name {}
variable "aks_node_count" {}
variable "aks_dns_prefix" {}
variable "aks_admin_username" {}
variable "aks_k8s_version" {}
variable "storage_container_name" {}
