variable "resource_group_name" {}
variable "location" {}
variable "storage_account_name" {}
variable "account_tier" {}
variable "account_replication_type" {}
variable "storage_container_name" {}
variable "storage_service" {}
variable "blob_name" {}
variable "blob_type" {}