resources:
  - repo: self

trigger: none

variables:
#View adoCrednetials vars in ADO library
- group: adoCredentials
- name: gitRepo
  value: 'git@github.com:jorgyp/test_api.git'
- name: resourceGroup
  value: 'aksrg'
- name: clusterName
  value: 'aks-production-manage'

parameters:
- name: terraform_task
  type: string
  default: 'deploy'

stages: 
  - stage: deploy
    displayName: inject variables into manifest file (main.tf)
    jobs:
    - deployment: install_flux 
      pool:
        vmImage: 'ubuntu-latest'
      environment: install_flux
      strategy:
        runOnce:
          deploy:
            steps:
            - task: KubectlInstaller@0
              inputs:
                kubectlVersion: 'latest'

            - task: Kubernetes@1
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'k8s manage prod'
                namespace: 'flux'
                command: 'apply'
                useConfigurationFile: true
                configuration: 'https://raw.githubusercontent.com/fluxcd/flux/helm-0.10.1/deploy-helm/flux-helm-release-crd.yaml'

            - task: Kubernetes@1
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'k8s manage prod'
                namespace: 'flux'
                command: 'apply'
                useConfigurationFile: true
                arguments: -f 'https://raw.githubusercontent.com/fluxcd/flux/helm-0.10.1/deploy-helm/flux-helm-release-crd.yaml'

            - task: HelmInstaller@1
              inputs:
                helmVersionToInstall: 'latest'

            - task: HelmDeploy@0
              name: FluxCD
              displayName: Install Flux CD
              inputs:
                connectionType: 'None'
                namespace: 'fluxcd'
                command: 'upgrade'
                chartType: 'Name'
                chartName: 'fluxcd/flux'
                releaseName: 'flux'
                overrideValues: 'git.url=git@github.com:$(gitRepo),git.pollInterval=1m'

            - task: Kubernetes@1
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'k8s manage prod'
                namespace: 'flux'
                command: 'logs'
                arguments: 'deployment/flux | grep identity.pub | cut -d ''"'' -f2'