resources:
  - repo: self

trigger: none

variables:
#View adoCrednetials vars in ADO library
- group: adoCredentials
- name: repo
  value: 'git@github.com:jorgyp/test_api.git'
- name: resourceGroup
  value: 'aksrg'
- name: clusterName
  value: 'aks-production-manage'

parameters:
- name: terraform_task
  type: string
  default: 'deploy'

stages: 
  - stage: deploy
    displayName: inject variables into manifest file (main.tf)
    jobs:
    - deployment: install_flux 
      pool:
        vmImage: 'ubuntu-latest'
      environment: install_flux
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                az aks get-credentials --resource-group $(resourceGroup) --name $(clusterName)
                kubectl apply -f https://raw.githubusercontent.com/fluxcd/flux/helm-0.10.1/deploy-helm/flux-helm-release-crd.yaml
                kubectl create ns flux
                helm upgrade -i flux \
                --set helmOperator.create=true \
                --set helmOperator.createCRD=false \
                --set git.url=$repo \
                --namespace flux \
                fluxcd/flux
                sleep 60s

    - deployment: install_flux 
      pool:
        vmImage: 'ubuntu-latest'
      environment: install_flux
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                kubectl -n flux logs deployment/flux | grep identity.pub | cut -d '"' -f2
                echo "copy this key to git repository settings"
  