resources:
  - repo: self

trigger: none

variables:
#View adoCrednetials vars in ADO library
- group: adoCredentials
- name: gitRepo
  value: 'git@github.com:jorgyp/test_api.git'
- name: resourceGroup
  value: 'aksrg'
- name: clusterName
  value: 'aks-production-manage'

parameters:
- name: terraform_task
  type: string
  default: 'deploy'

stages:
  - stage: deploy
    displayName: inject variables into manifest file (main.tf)
    jobs:
    - deployment: install_flux 
      pool:
        vmImage: 'ubuntu-latest'
      environment: install_flux
      strategy:
        runOnce:
          deploy:
            steps:
            
                
            - task: Kubernetes@1
              inputs:
                connectionType: 'Azure Resource Manager'
                azureSubscriptionEndpoint: 'my main subscription(5f549d28-a506-4f2f-b44a-6b609a01e13f)'
                azureResourceGroup: 'aksrg'
                kubernetesCluster: 'aks-production-manage'
                namespace: 'flux'
                command: 'logs'
                arguments: '-l app=flux | grep identity.pub'
