trigger: none

variables:
#View adoCrednetials vars in ADO library
- group: adoCredentials
- name: environment
  value: "production"
- name: source 
  value: "../../../modules/backend"
- name: resource_group_name
  value: "aksrg"
- name: location
  value: "West US 2"
- name: storage_account_name
  value: "aksaccountsyag"
- name: storage_service
  value: "aksstorageservice"
- name: account_tier
  value: "Standard"
- name: account_replication_type
  value: "LRS"
- name: storage_container_name
  value: "statecontainer"
- name: manifest_location
  value: "backend"
- name: source_resource_group
  value: "../../../modules/resource_group"
- name: source_storage_account
  value: "../../../modules/storage_account"
- name: source_storage_container
  value: "../../../modules/storage_container"

parameters:
  - name: terraform_task
    type: string
    default: 'deploy'

stages: 
  - stage: deploy
    displayName: inject variables into manifest file (main.tf)
    jobs:
    - job: 
      pool:
        vmImage: 'ubuntu-latest'
      steps:    
        - script: |
            sed -i -e "s|\${source}|$(source)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${resourceGroupName}|$(resource_group_name)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${location}|$(location)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${storageAccountName}|$(storage_account_name)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${accountTier}|$(account_tier)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${accountReplicationType}|$(account_replication_type)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${storageContainerName}|$(storage_container_name)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${storageService}|$(storage_service)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${blobName}|$(blob_name)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${blobType}|$(blob_type)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${sourceResourceGroup}|$(source_resource_group)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${sourceStorageACccount}|$(source_storage_account)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            sed -i -e "s|\${sourceStorageContainer}|$(source_storage_container)|g" "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
            cat "$(Pipeline.Workspace)/s/deployments/$(environment)/$(manifest_location)/main.tf"
        - task: Bash@3 
          displayName: 'Terraform Init'
          inputs:
            targetType: inline
            workingDirectory: 'deployments/$(environment)/$(manifest_location)'
            script: 'terraform init'
        - task: Bash@3 
          displayName: 'Terraform Plan'
          inputs:
            targetType: inline
            workingDirectory: 'deployments/$(environment)/$(manifest_location)'
            script: 'terraform plan'
        - task: Bash@3 
          displayName: 'Terraform Apply'
          condition: and(succeeded(), eq('${{ parameters.terraform_task }}', 'deploy'))
          inputs:
            targetType: inline
            workingDirectory: 'deployments/$(environment)/$(manifest_location)'
            script: 'terraform apply -auto-approve'

        - task: Bash@3 
          displayName: 'Terraform Destroy'
          condition: and(succeeded(), eq('${{ parameters.terraform_task }}', 'destroy'))
          inputs:
            targetType: inline
            workingDirectory: 'deployments/$(environment)/$(manifest_location)'
            script: 'terraform destroy -auto-approve'
